@startuml
start

:材料購入;
fork
    :ご飯を炊く;
    fork again
        :野菜を切る;
        :肉を切る;
        :玉ねぎを炒める;
        :肉を炒める;
        :人参、じゃかいもを炒める;
        :水に加えて煮込む;
        :ルーを入れる;
end fork

:盛り付ける;
stop
@enduml
