@startuml
    left to right direction
    class 患者{
    }
    class 医師{
        + 医局
        + 診察記録
    ---
        + 診察()

    }
    class 医局{
        + 外科
        + 内科
        + 小児科
    }
    class 診察記録{
        + 患者
    }
    患者 "*" -- "1" 医師 : 診察 <
    医師 "*" --o "1" 医局 : 所属 >
    医師 "1" --> "*" 診察記録 :記録 >
    
@enduml