@startuml
hide footbox
participant 利用者 as user 
participant 予約画面 
activate user
    activate 予約画面
        user -> 予約画面 : ログイン()
        予約画面 -> 予約画面 : 予約()
        activate 予約画面
        'deactivate 予約画面
    deactivate 予約画面
deactivate user
@enduml