@startuml
left to right direction
[*] -> メニュー
メニュー -down-> 予約と確認 : : リンクをクリック/「予約と確認」画面へ遷移
予約と確認 -> あなたの順番 : 登録・確認を選択 / 「あなたの順番」画面へ遷移
あなたの順番 -> 予約と確認
予約と確認 -up-> メニュー : 取消を選択 / メニュー画面へ戻る
' あなたの順番 -> メニュー
メニュー -down-> 今の順番 : リンクをクリック
今の順番 -> メニュー
メニュー -> [*]
@enduml