@startuml
[*] -> メニュー
メニュー -> 予約と確認 : : リンクをクリック/「予約と確認」画面へ遷移
メニュー -down-> 今の順番 : リンクをクリック
予約と確認 -> あなたの順番 : 登録・確認を選択 / 「あなたの順番」画面へ遷移
予約と確認 -> メニュー : 取消を選択 / メニュー画面へ戻る
今の順番 -> メニュー
あなたの順番 -> [*]
@enduml