@startuml
left to right direction
actor 利用者 as user
actor 看護師 as doctor
rectangle 予約システム {
    usecase メニュー
    usecase 予約と確認
    usecase あなたの順番
    usecase 今の順番
}
user --> メニュー
user --> 予約と確認
user --> 今の順番
user --> あなたの順番
今の順番 <-- doctor
@enduml