@startuml
hide circle
class ライントレーサー
class 光センサー
class CPU
class 左モーター
class 右モーター
class 電源SW
ライントレーサー "1" *-- "1" 光センサー
ライントレーサー "1" *-- "1" CPU
ライントレーサー "1" *-- "1" 左モーター
ライントレーサー "1" *-- "1" 右モーター
ライントレーサー "1" *-- "1" 電源SW
@enduml