@startuml
hide circle
class 注文{
    合計
}
class 注文明細{
    数量
    合計
}
class 割引クーポン{
    値引額
    期限
}
class カップ{
    サイズ
}
class ドリンク{
    種別
}
class 商品{
    名称
    単価
}
class ハンバーガー
class レシピ
class フード{
    種別
}
class ポテト{
    サイズ
}
class 材料
class パン
class 肉
class 野菜
class チーズ

注文 "1.." o--right- "*" 注文明細
注文明細 "0..*"--right- "0..1" 割引クーポン
注文明細 "0..*" --down- "1" 商品
カップ "1..3" --right- "0..*" ドリンク 
商品 <|--left- ドリンク
商品 <|--down- ハンバーガー
ハンバーガー "1" --right- "1" レシピ
ハンバーガー  <|-- フード
ハンバーガー  <|-- ポテト
フード "1..*" o--left- "1..*" 材料
材料 <|-- パン
材料 <|-- 肉
材料 <|-- 野菜
材料 <|-- チーズ
@enduml