@startuml
left to right direction
actor 客 as customer
actor ベンダー as bender
rectangle 自動販売機 {
    usecase 料金装置
    usecase ボタン
    usecase ベンダー装置
}
customer --> 料金装置 
customer --> ボタン
customer --> ベンダー装置 
bender --> 自動販売機
@enduml